### PR TITLE
KB-13 03/02/2021 Update the settings.py and docker-compose files suc…

### PR DESCRIPTION
**Pull request by bunny0310**
…h that the database configuration values are pulled in from the env file instead of relying on the hardcoded values

### CODE REVIEW

**Comment by marcinknara** [comment]
Pull requests should not be past-tense (it's a weird syntax, but it's the practice). For example, in this case, you would want to write: "Update the settings.py and docker-compose files..."

**Comment by bunny0310** [comment]
@marcinknara done.

**Review by marcinknara — APPROVED** [review]
Looking good

**Comment by Enoch-Hsiao** [comment]
I know it's merged in, but the .env file got to be in .gitignore. We can't expose passwords and keys on public repos.

**Pull request merged**
